### ISSUE TITLE
'-Wincompatible-pointer-types' diagnostics cause build failure with GCC 14

### ISSUE THREAD

**Issue by Leo3418** [mjakeman/text-engine#37]
Several files' compilation will trigger `-Wincompatible-pointer-types` diagnostics.  This will prevent the project from being successfully built on Fedora 40 and other GNU/Linux distributions that use GCC 14 because, on GCC 14, `-Wincompatible-pointer-types` is treated as an error rather than a warning.

Steps to reproduce:

1. Clone this repository and enter the directory that contains the clone.
2. If `gcc --version` reports GCC 14 or above, then run `meson setup build`;
   Otherwise, run `CFLAGS="-Werror=incompatible-pointer-types" meson setup build`.
3. Run `meson compile -C build`.

[build.log](https://github.com/mjakeman/text-engine/files/15210610/build.log)

**Comment by prstephens** [comment]
any update on this issue? its stopping me installing a few AUR packages that depend on text-engine.

**Comment by prathamvbhat** [comment]
I get this error when i follow the guide.

[18/42] Compiling C object src/libtext-engine-0.1.so.0.p/text-engine.c.o
ninja: build stopped: subcommand failed.
