### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by hellsworth** [mjakeman/text-engine#7]
Hi, @mjakeman I'd like to package this for debian but I see you've changed the licence after the v0.1.0 release. So would you mind making a new release so I can package it with just the LGPL?

I've also packaged [extension-manager](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007935) and [blueprint-compiler](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007936) for debian too, in case you didn't know. so :wave

**Comment by mjakeman** [comment]
Hi @hellsworth,

Awesome to see a debian package, thanks for the interest!

I've tagged a new minor release [v0.1.1](https://github.com/mjakeman/text-engine/releases/tag/v0.1.1) with the license change included. Let me know if you run into any other issues :slightly_smiling_face:
